config/routes.rb
Kngroo::Application.routes.draw do

  resources :users, :only => [ :new, :create ]
  resource :user, :only => [ :show, :update, :destroy ] do
    resources :hops, :controller => 'users/hops', :only => [ :index, :show ]
    resources :assignments, :only => [ :index, :create, :destroy ] do
      resources :venues, :only => :show do
        resources :trivias, :only => [ :index ]
        resources :checkins, :only => :create
      end
    end
    resources :attempts, :only => [ :create ]
  end
  resources :sessions, :only => :new
  resource :session, :only => [ :create, :destroy ]
  match '/sign_in' => 'sessions#new', :via => :get, :as => 'sign_in'
  match '/sign_up' => 'users#new', :via => :get, :as => 'sign_up'
  match '/sign_out' => 'sessions#destroy', :via => [:get,:delete], :as => 'sign_out'
  
  resources :hops, :only => [ :create, :index, :show, :update, :destroy ] do
    resources :venues, :controller => 'hops/venues', :only => [ :index, :show, :update, :destroy ] do
      collection do
        post :search
      end
      resources :trivias, :only => [ :create, :update, :destroy ]
    end
    member do
      get :publish
    end
  end
  resources :memberships, :only => [ :create, :destroy ]
  resources :leaders, :only => [ :index ]
  resources :categories, :only => [ :index ]
  
  root :to => 'home#index'
  

end

app/models/hop.rb
class Hop < ActiveRecord::Base

  belongs_to :category
  has_many :memberships
  has_many :venues, :through => :memberships
  has_many :assignments
  has_many :users, :through => :assignments
  has_many :checkins, :through => :assignments
  has_many :trivias
  has_many :trophies
  
  validates_presence_of :title, :description, :points
  validates_numericality_of :points
  
  has_attached_file :stamp,
    :storage => :s3, 
    :s3_credentials => "config/s3.yml",
    :s3_protocol => 'https',
    :path => "/hops/:id/stamp"
    
  has_attached_file :image,
    :storage => :s3,
    :s3_credentials => "config/s3.yml",
    :s3_protocol => 'https',
    :path => "/hops/:id/image"
  
  default_scope :order => 'title asc'
  scope :published, where('published_at <= ?',Time.now)
  
  def published?
    published_at!=nil && published_at < Time.now  
  end
  
  def ready_for_publication?
    !venues.empty? && venues.reject {|v| Trivia.exists?(:hop_id => id, :venue_id => v.id)}.empty?
  end

  def stamp_url
    stamp.url
  end
  
  def image_url
    image.url
  end
  
end

app/controllers/hops/venues_controller.rb
class Hops::VenuesController < ApplicationController

  before_filter :authorize
  before_filter :assign_hop
  before_filter :assign_venue, :only => [ :show, :update, :destroy ]
  
  def index
    @venues = @hop.venues
    respond_to do |format|
      format.html
      format.json { render :json => @venues }
    end
  end
  
  def show
    respond_to do |format|
      format.html
      format.json { render json: @venue }
    end
  end
  
  # def checkin
  #   @checkin = Checkin.new(:assignment_id => Assignment.find_by_hop_id_and_user_id(@hop.id, current_user.id).id, :venue_id => @venue.id)
  #   respond_to do |format|
  #     if @checkin.save
  #       format.html { redirect_to hop_venue_path(@hop,@venue) }
  #       format.json { render :json => @checkin.to_json(:methods => :trophy_awarded) }
  #     else
  #       format.html { redirect_to hop_venue_path(@hop, @venue), :alert => @checkin.errors.full_messages.join("<br/>") }
  #       format.json { render :json => { :errors => @checkin.errors.full_messages } }
  #     end
  #   end
  # end
  
  def update
    if @venue.update_attributes(params[:venue])
      redirect_to [@hop,@venue]
    else
      redirect_to [@hop,@venue], :alert => @venue.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @hop.venues.delete @venue
    redirect_to @hop
  end
  
  def search
    if params[:sw] && params[:ne] && params[:query]
      rsp = Foursquare::Venue.search(sw:params[:sw],ne:params[:ne],query:params[:query].gsub(/ /,"+"),intent:"browse",limit:params[:limit])
    else
      rsp = Foursquare::Venue.search(ll:"#{params[:lat]},#{params[:lng]}",radius:25000,intent:"browse",query:params[:query].gsub(/ /,"+"))
    end
    @venues = []
    if rsp['meta']['code']==400
      @error = rsp['meta']['errorDetail']
    else
      groups = rsp['response']['groups']
      if groups && !groups.empty?
        items = groups.first['items']
        for item in items
          venue = Venue.find_or_create_by_name(item['name'])
          venue.address = item['location']['address']
          venue.lat = item['location']['lat']
          venue.lng = item['location']['lng']
          venue.save
          @venues << venue
        end
      end
    end
    @venues = @venues - @hop.venues
    
    respond_to do |format|
      format.js { render :layout => false }
    end
  end
  
  def assign_hop
    @hop = Hop.find(params[:hop_id]) if params[:hop_id]
    # deny_access unless @hop.users.include?(current_user)
  end
  
  def assign_venue
    @venue = Venue.find(params[:id])
  end
  
end

app/controllers/hops_controller.rb
class HopsController < ApplicationController

  before_filter :authorize, :except => :index
  
  def index
    if signed_in? && current_user.has_role?('admin')
      @hops = Hop.includes(:venues).all
    elsif signed_in? && current_user.has_role?('user')
      @hops = Hop.published.includes(:venues).all - Assignment.active.where(:user_id => current_user.id).map(&:hop)
    else
      @hops = Hop.published.includes(:venues).all
    end

    respond_to do |format|
      format.html
      format.json { render :json => @hops.to_json(:include => :venues, :methods => [ :stamp_url, :image_url ]) }
    end
  end
  
  def create
    @hop = Hop.new(params[:hop])
    if @hop.save
      redirect_to @hop
    else
      redirect_to hops_path, :alert => @hop.errors.full_messages.join("<br/>")
    end
  end
  
  def show
    @hop = Hop.includes(:venues).find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @hop.to_json(:include => :venues) }
    end
  end
  
  def update
    @hop = Hop.find(params[:id])
    if @hop.update_attributes(params[:hop])
      redirect_to @hop
    else
      redirect_to @hop, :alert => @hop.errors.full_messages.join("<br/>")
    end
  end
  
  def destroy
    @hop = Hop.find(params[:id])
    @hop.destroy
    redirect_to hops_path
  end
  
  def publish
    @hop = Hop.find(params[:id])
    deny_access unless current_user.has_role?('admin')
    @hop.published_at = Time.now
    @hop.save
    redirect_to @hop
  end
  
end

app/controllers/users/hops_controller.rb
class Users::HopsController < ApplicationController

  before_filter :authorize
  
  def index
    @hops = Hop.includes(:venues,:checkins).joins(:assignments).where(['assignments.user_id = ?',current_user.id]) #.where(['checkins.user_id = ?',current_user.id])
    respond_to do |format|
      format.html
      format.json { render :json => @hops.to_json(:include => [ :venues, :checkins ]) }
    end
  end
  
  def show
    @hop = Hop.includes(:venues, :checkins).joins(:assignments).where(['assignments.user_id = ?',current_user.id]).find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @hop.to_json(:include => [ :venues, :checkins ]) }
    end
  end
  
end

app/helpers/hops/venues_helper.rb
module Hops::VenuesHelper
end

app/helpers/hops_helper.rb
module HopsHelper
end

app/helpers/users/hops_helper.rb
module Users::HopsHelper
end

app/views/hops/index.haml
- if signed_in? && current_user.has_role?('admin')
	%h1 All Hops
- else
	%h1 Find a Hop
- if @hops.empty?
	%p No available hops
- else
	%table.hops
		%tr
			%th NAME
			%th CATEGORY
			%th PUBLISHED AT
			%th FEATURED
			%th
		- for hop in @hops
			%tr
				%td= link_to hop.title, hop
				%td= hop.category.title unless hop.category.nil?
				%td= hop.published_at.to_s
				%td= hop.featured? ? "YES" : "NO"
				%td
					= link_to "delete", hop, :method => :delete, :class => 'trash'

- if signed_in? && current_user.may_create_hop?
	%p.control= link_to_function "Add Hop", "$('#add_hop').dialog({modal:true,title:'Create a Hop',width:'800px'})"
	#add_hop{:style => "display:none"}
		= form_for Hop.new do |f|
			%p
				= f.label :title
				= f.text_field :title
			%p
				= f.label :category_id
				= f.collection_select :category_id, Category.all, :id, :title
			%p
				= f.label :points
				= f.text_field :points, :size => 4
			%p
				= f.label :description
				= f.text_area :description, :rows => 4, :cols => 20
			%p.control= f.submit "Create Hop"

app/views/hops/show.haml
= content_for :breadcrumb do
	= link_to "All Hops", hops_path
	»

#hop
	%h1 Hop: #{@hop.title}
	.detail
		%p.control
			%label Status: 
			- if @hop.published?
				Published
			- else
				Draft
				- if @hop.venues.empty?
					%span You must add at least one venue before you may publish this hop.
				- elsif @hop.ready_for_publication?
					= link_to "Publish Now", publish_hop_path(@hop), :class => 'clock text'
				- else
					%span You must add a trivia question to each venue before you may publish this hop.
		%p.control
			- if @hop.featured?
				%label Featured: 
				Yes
				= form_for @hop do |f|
					= f.hidden_field :featured, :value => false
					= f.submit "Un-Feature"
			- else
				%label Featured: 
				No
				= form_for @hop do |f|
					= f.hidden_field :featured, :value => true
					= f.submit "Feature"
		%p.control
			%label Category:
			= form_for @hop do |f|
				= f.collection_select :category_id, Category.all, :id, :title, {}, { :onchange => "form.submit()" }
		%p.control
			%label Image:
			- if @hop.image_file_name.blank?
				No hop image
			- else
				= image_tag @hop.image.url
			= form_for @hop, :html => { :multipart => true } do |f|
				= f.file_field :image
				= f.submit "Upload Hop Image"
		%p.control
			%label Stamp:
			- if @hop.stamp_file_name.blank?
				No stamp image
			- else
				= image_tag @hop.stamp.url
			= form_for @hop, :html => { :multipart => true } do |f|
				= f.file_field :stamp
				= f.submit "Upload Stamp Image"
	.venues
		%h2 Venues
		- if @hop.venues.empty?
			%p No venues
		- else
			%ul
				- for venue in @hop.venues
					%li
						= link_to venue.name, [@hop,venue]
						= link_to "delete", [@hop,venue], :method => :delete, :class => "trash"

- if signed_in? && current_user.may_update_hop?(@hop)
	%p.control= link_to_function "Add Venue", "$('#add_venue').dialog({modal:true,title:'Find a Venue',width:'800px'});showMap()"
	#add_venue{:style => "display:none"}
		.search
			= form_for :venue, :url => search_hop_venues_path(@hop), :remote => true, :id => "venue_search" do |f|
				= hidden_field_tag "sw", "27.6657260197085,-82.73374998029151"
				= hidden_field_tag "ne", "27.8657260197085,-82.53374998029151"
				%label Enter a name:
				= text_field_tag :query
				= f.submit "Search", :class => 'text circleplus', :onclick => "$('#add_venue .search .activity').show()"
				%span.radio
					= radio_button_tag "limit", 10, :selected => true
					%label{:for => "limit_10"} 10
					= radio_button_tag "limit", 20
					%label{:for => "limit_20"} 20
					= radio_button_tag "limit", 50
					%label{:for => "limit_50"} 50
				= image_tag 'activity.gif', :width => 25, :height => 25, :class => 'activity', :style => "display:none"
			/ = link_to_function "Enter Address", "alert('center map on address')"
			%hr
		.results
			.list
				Enter a name above to get started.
			#map
			%hr
	/ #add_venue.tabs{:style => "display:none"}
	/ 	%ul
	/ 		%li= link_to "Select Existing", '#existing_venue'
	/ 		%li= link_to "Create New", '#new_venue'
	/ 	#existing_venue
	/ 		= form_for Membership.new do |f|
	/ 			= f.hidden_field :hop_id, :value => @hop.id
	/ 			%p
	/ 				= f.label :venue_id
	/ 				= f.collection_select :venue_id, Venue.all-@hop.venues, :id, :name
	/ 			%p.control= f.submit "Add Venue to Hop"
	/ 	#new_venue
	/ 		= form_for Membership.new do |f|
	/ 			= f.hidden_field :hop_id, :value => @hop.id
	/ 			= f.fields_for :venue_attributes do |v|
	/ 				%p
	/ 					= v.label :name
	/ 					= v.text_field :name
	/ 			%p.control= f.submit "Create Venue"